services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1111:1111" # Map host port 1111 to container port 1111
    volumes:
      # Mount your Firebase service account key into the container
      # IMPORTANT: Replace './firebase-service-account-key.json'
      # with the actual path to your service account key file.
      - ./firebase-service-account-key.json:/usr/src/app/firebase-service-account-key.json:ro
    environment:
      - NODE_ENV=production
      # IMPORTANT: Set these environment variables
      - PORT=1111
      - GITHUB_PAT=github_pat_skibidi_toilet # GitHub Fine-grained Token, use the same one in the parent directory's .env file
      - GITHUB_OWNER=Nova-Haven # GitHub username or organization
      - GITHUB_REPO=Maquilinventario # GitHub repository name
      - FIREBASE_SERVICE_ACCOUNT_PATH=/usr/src/app/firebase-service-account-key.json
      # Your Firebase Project ID, needed for verifying ID tokens against the correct project
      - FIREBASE_PROJECT_ID=project-name
      # The origin of your frontend app for CORS
      - FRONTEND_ORIGIN=https://project-name.web.app
    restart: unless-stopped
